export const HELLO_WRITING = [
  'One step closer to your best self. 🌟',
  "Keep showing up. You're doing amazing. 💪",
  'Win the day, one habit at a time. 🏆',
  'Every small action builds a stronger you. 💥',
  'Progress over perfection — always. 🚀',
  'You’ve got this. Always cheering for you! 🎉',
  'A new day, a new chance to grow. 🌱',
  'You’re doing better than you think. 💫',
  'Take it slow, but never stop. 🐢💨',
  'Your effort matters, every single day. ⏳',
  'Let’s crush today! 💥',
  'Back at it again — go get it! 🔥',
  'Ready to win yourself today? 🏅',
  'Time to flex those habits 💪',
  'Who’s the boss? You are. 😎',
] as const;
